name: Template Compliance

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  Compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Setup Python
        uses: actions/setup-python@v4
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run the compliance function
        run: |
          git config --global user.email "bot@jso.com"
          git config --global user.name "{{ PackageName }} workflow"
          julia --project -e 'using {{ PackageName }}; {{ PackageName }}.template_compliance(ENV["REPO"])'
        env:
          GITHUB_TOKEN: ${{ secrets.{{ PackageName }}_TOKEN }}
          REPO: ${{ matrix.repo }}
